#!/bin/bash
#Script to write to InfluxDB for CyberPower UPS Satistics
#This script requires the pwrstat utility to be installed and running on the system
#Written by BarryDinpoon

#Input InfluxDB information here
DBUSER=<InfluxDBUser>
DBPASS=<InfluxDBPassword>
DBHOST=<InfluxDBHost>
DBPORT=<InfluxDBPort>
DBNAME=<InfluxDBName>

while true; do

# Collect the stats
STATS=$(pwrstat -status)

#Gather Values for statistics
LOAD=$(echo -e "$STATS" |grep Load | cat | awk '{print $2}')
RUNTIME=$(echo -e "$STATS" |grep Remaining | cat | awk '{print $3}')
UTILVOLT=$(echo -e "$STATS" |grep "Utility Voltage" | cat | awk '{print $3}')
OUTVOLT=$(echo -e "$STATS" |grep "Output Voltage" | cat | awk '{print $3}')
BATTCAP=$(echo -e "$STATS" |grep "Battery Capacity" | cat | awk '{print $3}')
SUPPLY=$(echo -e "$STATS" |grep "Power Supply" | cat | awk '{print $4}')
STATE=$(echo -e "$STATS" |grep "State" | cat | awk '{print $2}')
RATING=$(echo -e "$STATS" |grep "Rating Power" | cat | awk '{print $3}')
LOADPERCENT=$(echo "scale=2;($LOAD/$RATING)" | bc -l)

#Check Power Supply, 1 = Utility Power, 0 = Battery Power
if [ $SUPPLY == "Utility" ]; then
	SUPPLY="1"
else
	SUPPLY="0"
fi
#Check State, 1 = Normal, 0 = Other
if [ $STATE == "Normal" ]; then
	STATE="1"
else
	STATE="0"
fi

#Write out to InfluxDB
/usr/bin/curl -s -i -XPOST -u $DBUSER:$DBPASS "http://$DBHOST:$DBPORT/write?db=$DBNAME" --data-binary  "power_status,host=$HOSTNAME success=0,load=$LOAD,runtime=$RUNTIME,utility_voltage=$UTILVOLT,output_voltage=$OUTVOLT,battery_capacity=$BATTCAP,power_supply=$SUPPLY,power_state=$STATE,ups_rating=$RATING,load_percentage=$LOADPERCENT" > /dev/null

#Wait 2 seconds
sleep 2s
done
